# Generated by Django 3.2.19 on 2024-09-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('pressing_manager', 'Pressing Manager'), ('deliver', 'Deliver'), ('client', 'Client')], default='client', max_length=30),
        ),
    ]
