# Generated by Django 5.0.6 on 2024-09-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_photo_pressingprofile_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='service_rate',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
