# Generated by Django 5.0.6 on 2024-09-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_message_contact_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressingprofile',
            name='number_of_pressings',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
