# Generated by Django 5.0.6 on 2024-09-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_receipt_remove_pressingprofile_number_of_pressings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressingprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pressingprofile',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pressingprofile',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pressingprofile',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
