# Generated by Django 5.0.6 on 2024-09-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_pressingprofile_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressingprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='pressingprofile',
            name='city',
            field=models.CharField(default='Yaoundé', max_length=255),
        ),
        migrations.AddField(
            model_name='pressingprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pressingprofile',
            name='quarter',
            field=models.CharField(default='Mendong', max_length=255),
        ),
        migrations.AddField(
            model_name='pressingprofile',
            name='region',
            field=models.CharField(default='Center', max_length=255),
        ),
        migrations.AddField(
            model_name='pressingprofile',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
