# Generated by Django 5.0.6 on 2024-09-10 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_pressingprofile_location_pressingprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='pressing_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photo_set', to='orders.pressingprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='pressing_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='video_set', to='orders.pressingprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='pressingprofile',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='orders.photo'),
        ),
        migrations.AlterField(
            model_name='pressingprofile',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='orders.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
