# Generated by Django 5.0.6 on 2024-09-10 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_region_town_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressingprofile',
            name='town',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.town'),
        ),
    ]
