# Generated by Django 5.0.6 on 2024-09-12 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressingprofile',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='pressingprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pressingprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pressingprofile',
            name='photos',
        ),
        migrations.AlterField(
            model_name='pressingprofile',
            name='pressing_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pressingprofile',
            name='quarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.quarter'),
        ),
        migrations.AlterField(
            model_name='pressingprofile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.region'),
        ),
        migrations.AlterField(
            model_name='pressingprofile',
            name='telephone_number',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='pressingprofile',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.town'),
        ),
        migrations.RemoveField(
            model_name='pressingprofile',
            name='videos',
        ),
        migrations.CreateModel(
            name='PressingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='orders.pressingprofile')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.quarter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.region')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.town')),
            ],
        ),
        migrations.AddField(
            model_name='pressingprofile',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='pressingprofile',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
