# Generated by Django 5.0.6 on 2024-09-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_pressingprofile_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressingprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED')], default='pending', max_length=50),
        ),
    ]
