# Generated by Django 5.0.6 on 2024-10-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_pressingprofile_predefined_pressingprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressingprofile',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
