# Generated by Django 5.0.6 on 2024-10-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_pressingprofile_latitude_pressingprofile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressingprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='pressingprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True),
        ),
    ]
