# Generated by Django 5.0.6 on 2024-10-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_pressingprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='read',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
