# Generated by Django 5.0.6 on 2024-10-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_chatmessage_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='media',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
