# Generated by Django 5.0.6 on 2024-10-08 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_remove_chatmessage_media_chatmessage_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicityCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('duration', models.IntegerField()),
                ('platforms', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pressing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pressingprofile')),
            ],
        ),
    ]
