# Generated by Django 5.0.6 on 2024-10-08 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_alter_rating_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='delivery_service',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='delivery_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.deliveryuser'),
        ),
        migrations.DeleteModel(
            name='DeliveryService',
        ),
    ]
