# Generated by Django 5.0.6 on 2024-10-08 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_deliveryuser_remove_rating_delivery_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='delivery_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='date_rated',
        ),
        migrations.AddField(
            model_name='rating',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='DeliveryUser',
        ),
    ]
