# Generated by Django 5.0.6 on 2024-10-08 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_rating_delivery_user_remove_rating_date_rated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveries_completed', models.IntegerField(default=0)),
                ('client_recuperation', models.IntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, default=60000.0, max_digits=10)),
                ('delivery_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
